import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { execSync } from 'child_process';

const execSyncWrapper = (command) => {
  let stdout = null;
  try {
    stdout = execSync(command).toString().trim();
  } catch (error) {
    console.error(error);
  }
  return stdout;
};

const main = () => {
  const gitBranch = execSyncWrapper('git rev-parse --abbrev-ref HEAD');
  const gitCommitHash = execSyncWrapper('git rev-parse --short=7 HEAD');

  const obj = {
    gitBranch,
    gitCommitHash
  };

  const filePath = resolve('src', 'autogenerated', 'gitInfo.json');
  const fileContents = JSON.stringify(obj, null, 2);

  writeFileSync(filePath, fileContents);
};

main();
